language: python

python:
  - '3.5'

install:
  - pip3 install HookTest==1.0.0

script: hooktest ./ --console table --scheme epidoc --workers 3 --verbose 10 --manifest --countword --hookUI "http://ci.perseids.org/api/hook/v2.0/user/repositories/OpenGreekAndLatin/First1KGreek" --allowfailure

before_deploy:
  - hooktest-build --travis ./
  - results=$(cat manifest.txt)
  - DATE=`date +%Y-%m-%d`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$major_version.$minor_version.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "$DATE" -m "PASSING FILES" -m "$results"
  - git push -q https://$GITPERM@github.com/OpenGreekAndLatin/First1KGreek --tags
  - ls -R

deploy:
  provider: releases
  api_key: $GITPERM
  file: release.tar.gz
  skip_cleanup: true
  on:
    repo: OpenGreekAndLatin/First1KGreek
    branch: master

env:
  global:
    major_version: 1
    minor_version: 1
